/**
 * Widget Registry — central JSON catalog of all available widgets.
 * Each entry defines: id, name, description, category, icon (lucide name),
 * component path, defaultSize, minSize, defaultConfig.
 */

export const WIDGET_REGISTRY = {
  // ── Market ─────────────────────────────────────────────────────────────────
  'market-overview': {
    id: 'market-overview',
    name: 'Market Overview',
    description: 'Live indices ticker bar (S&P 500, NASDAQ, Dow, etc.)',
    category: 'market',
    icon: 'Globe',
    componentPath: 'widgets/MarketOverview',
    defaultSize: { w: 12, h: 2 },
    minSize:     { w: 6,  h: 2 },
    defaultConfig: {},
  },
  'live-watchlist': {
    id: 'live-watchlist',
    name: 'Live Watchlist',
    description: 'Real-time quote table for watched symbols',
    category: 'market',
    icon: 'List',
    componentPath: 'widgets/LiveWatchlist',
    defaultSize: { w: 8, h: 6 },
    minSize:     { w: 4, h: 4 },
    defaultConfig: {},
  },
  'ticker-info': {
    id: 'ticker-info',
    name: 'Ticker Information',
    description: 'Quote card with mini sparkline chart',
    category: 'stock',
    icon: 'Info',
    componentPath: 'widgets/TickerInformation',
    defaultSize: { w: 4, h: 3 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: { symbol: 'AAPL' },
  },
  'stock-chart': {
    id: 'stock-chart',
    name: 'Stock Chart',
    description: 'Interactive OHLC/line/area chart with technical indicators',
    category: 'stock',
    icon: 'CandlestickChart',
    componentPath: 'widgets/ChartWidget',
    defaultSize: { w: 8, h: 6 },
    minSize:     { w: 4, h: 4 },
    defaultConfig: { symbol: 'AAPL', chartType: 'candlestick', period: '3mo' },
  },
  'financial-table': {
    id: 'financial-table',
    name: 'Financial Table',
    description: 'Income statement / balance sheet / cash flow table',
    category: 'stock',
    icon: 'Table2',
    componentPath: 'widgets/FinancialTableWidget',
    defaultSize: { w: 6, h: 5 },
    minSize:     { w: 4, h: 4 },
    defaultConfig: { symbol: 'AAPL', statement: 'income' },
  },
  'revenue-segments': {
    id: 'revenue-segments',
    name: 'Revenue Segments',
    description: 'Revenue breakdown by product/geography',
    category: 'stock',
    icon: 'PieChart',
    componentPath: 'widgets/RevenueSegmentsWidget',
    defaultSize: { w: 6, h: 5 },
    minSize:     { w: 4, h: 4 },
    defaultConfig: { symbol: 'AAPL' },
  },
  'key-metrics': {
    id: 'key-metrics',
    name: 'Key Metrics',
    description: 'Valuation ratios, margins, growth rates',
    category: 'stock',
    icon: 'Target',
    componentPath: 'widgets/KeyMetricsWidget',
    defaultSize: { w: 4, h: 4 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: { symbol: 'AAPL' },
  },
  'analyst': {
    id: 'analyst',
    name: 'Analyst Ratings',
    description: 'Wall Street analyst price targets and recommendations',
    category: 'stock',
    icon: 'Users',
    componentPath: 'widgets/AnalystWidget',
    defaultSize: { w: 4, h: 4 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: { symbol: 'AAPL' },
  },
  'earnings': {
    id: 'earnings',
    name: 'Earnings',
    description: 'EPS estimates vs actuals, surprise history',
    category: 'stock',
    icon: 'TrendingUp',
    componentPath: 'widgets/EarningsWidget',
    defaultSize: { w: 5, h: 4 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: { symbol: 'AAPL' },
  },
  'earnings-history': {
    id: 'earnings-history',
    name: 'Earnings History',
    description: 'Historical EPS and revenue chart',
    category: 'stock',
    icon: 'BarChart2',
    componentPath: 'widgets/EarningsHistoryWidget',
    defaultSize: { w: 5, h: 4 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: { symbol: 'AAPL' },
  },
  'dividend': {
    id: 'dividend',
    name: 'Dividend',
    description: 'Dividend yield, payout history, ex-dates',
    category: 'stock',
    icon: 'DollarSign',
    universal: true,              // rendered by UniversalWidget + widgetConfigs.jsx
    defaultSize: { w: 4, h: 3 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: { symbol: 'AAPL' },
  },
  'insider': {
    id: 'insider',
    name: 'Insider Transactions',
    description: 'Recent insider buy/sell transactions',
    category: 'stock',
    icon: 'UserCheck',
    componentPath: 'widgets/InsiderWidget',
    defaultSize: { w: 5, h: 4 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: { symbol: 'AAPL' },
  },
  'swot': {
    id: 'swot',
    name: 'SWOT Analysis',
    description: 'AI-generated SWOT analysis',
    category: 'stock',
    icon: 'Layers',
    componentPath: 'widgets/SWOTWidget',
    defaultSize: { w: 5, h: 5 },
    minSize:     { w: 4, h: 4 },
    defaultConfig: { symbol: 'AAPL' },
  },
  'management': {
    id: 'management',
    name: 'Management',
    description: 'Executive team and board information',
    category: 'stock',
    icon: 'Briefcase',
    componentPath: 'widgets/ManagementWidget',
    defaultSize: { w: 4, h: 4 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: { symbol: 'AAPL' },
  },
  'economic-moat': {
    id: 'economic-moat',
    name: 'Economic Moat',
    description: 'Competitive advantage analysis',
    category: 'stock',
    icon: 'Shield',
    componentPath: 'widgets/EconomicMoatWidget',
    defaultSize: { w: 4, h: 4 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: { symbol: 'AAPL' },
  },
  'stock-sentiment': {
    id: 'stock-sentiment',
    name: 'Stock Sentiment',
    description: 'News and social sentiment for the ticker',
    category: 'stock',
    icon: 'MessageSquare',
    componentPath: 'widgets/StockSentimentWidget',
    defaultSize: { w: 4, h: 3 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: { symbol: 'AAPL' },
  },
  'social-sentiment': {
    id: 'social-sentiment',
    name: 'Social Sentiment',
    description: 'Reddit / Twitter sentiment trends',
    category: 'stock',
    icon: 'Hash',
    componentPath: 'widgets/SocialSentimentWidget',
    defaultSize: { w: 4, h: 3 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: { symbol: 'AAPL' },
  },
  'investment-scorecard': {
    id: 'investment-scorecard',
    name: 'Investment Scorecard',
    description: 'Composite investment quality score',
    category: 'stock',
    icon: 'Star',
    componentPath: 'widgets/InvestmentScorecardWidget',
    defaultSize: { w: 4, h: 4 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: { symbol: 'AAPL' },
  },
  'company-filings': {
    id: 'company-filings',
    name: 'Company Filings',
    description: 'SEC filings (10-K, 10-Q, 8-K)',
    category: 'stock',
    icon: 'FileText',
    universal: true,              // rendered by UniversalWidget + widgetConfigs.jsx
    defaultSize: { w: 5, h: 4 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: { symbol: 'AAPL' },
  },
  'stock-splits': {
    id: 'stock-splits',
    name: 'Stock Splits',
    description: 'Historical stock split history',
    category: 'stock',
    icon: 'Scissors',
    universal: true,              // rendered by UniversalWidget + widgetConfigs.jsx
    defaultSize: { w: 4, h: 3 },
    minSize:     { w: 3, h: 2 },
    defaultConfig: { symbol: 'AAPL' },
  },
  'company-relations': {
    id: 'company-relations',
    name: 'Company Relations',
    description: 'Suppliers, customers, competitors graph',
    category: 'stock',
    icon: 'Network',
    componentPath: 'widgets/CompanyRelationsWidget',
    defaultSize: { w: 6, h: 5 },
    minSize:     { w: 4, h: 4 },
    defaultConfig: { symbol: 'AAPL' },
  },
  'macro-cross': {
    id: 'macro-cross',
    name: 'Macro Cross',
    description: 'Cross-asset macro correlation view',
    category: 'stock',
    icon: 'GitBranch',
    componentPath: 'widgets/MacroCrossWidget',
    defaultSize: { w: 6, h: 4 },
    minSize:     { w: 4, h: 3 },
    defaultConfig: { symbol: 'AAPL' },
  },

  // ── Macro ──────────────────────────────────────────────────────────────────
  'macro-chart': {
    id: 'macro-chart',
    name: 'Macro Chart',
    description: 'Economic indicator time-series chart',
    category: 'macro',
    icon: 'TrendingUp',
    componentPath: 'widgets/macro/MacroChartWidget',
    defaultSize: { w: 6, h: 4 },
    minSize:     { w: 4, h: 3 },
    defaultConfig: { indicator: 'fed_rate' },
  },
  'regime': {
    id: 'regime',
    name: 'Market Regime',
    description: 'Current economic / market regime classification',
    category: 'macro',
    icon: 'Activity',
    componentPath: 'widgets/macro/RegimeWidget',
    defaultSize: { w: 4, h: 3 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: {},
  },
  'yield-curve': {
    id: 'yield-curve',
    name: 'Yield Curve',
    description: 'US Treasury yield curve shape',
    category: 'macro',
    icon: 'GitMerge',
    componentPath: 'widgets/macro/YieldCurveWidget',
    defaultSize: { w: 5, h: 4 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: {},
  },
  'yield-curve-snapshot': {
    id: 'yield-curve-snapshot',
    name: 'Yield Curve Snapshot',
    description: 'Comparative yield curve snapshot',
    category: 'macro',
    icon: 'Camera',
    componentPath: 'widgets/macro/YieldCurveSnapshotWidget',
    defaultSize: { w: 5, h: 4 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: {},
  },
  'yield-trends': {
    id: 'yield-trends',
    name: 'Yield Trends',
    description: '2Y/10Y spread and yield trends',
    category: 'macro',
    icon: 'TrendingDown',
    componentPath: 'widgets/macro/YieldTrendsWidget',
    defaultSize: { w: 5, h: 4 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: {},
  },
  'inflation-trends': {
    id: 'inflation-trends',
    name: 'Inflation Trends',
    description: 'CPI, PPI, PCE inflation trends',
    category: 'macro',
    icon: 'Flame',
    componentPath: 'widgets/macro/InflationTrendsWidget',
    defaultSize: { w: 5, h: 4 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: {},
  },
  'inflation-decomp': {
    id: 'inflation-decomp',
    name: 'Inflation Decomposition',
    description: 'CPI component breakdown',
    category: 'macro',
    icon: 'Layers',
    componentPath: 'widgets/macro/InflationDecompWidget',
    defaultSize: { w: 5, h: 4 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: {},
  },
  'inflation-momentum': {
    id: 'inflation-momentum',
    name: 'Inflation Momentum',
    description: 'MoM / YoY inflation momentum',
    category: 'macro',
    icon: 'Zap',
    componentPath: 'widgets/macro/InflationMomentumWidget',
    defaultSize: { w: 5, h: 4 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: {},
  },
  'labor-market': {
    id: 'labor-market',
    name: 'Labor Market',
    description: 'Unemployment, payrolls, JOLTS',
    category: 'macro',
    icon: 'Users',
    componentPath: 'widgets/macro/LaborMarketWidget',
    defaultSize: { w: 5, h: 4 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: {},
  },
  'jobs-breakdown': {
    id: 'jobs-breakdown',
    name: 'Jobs Breakdown',
    description: 'Non-farm payrolls sector breakdown',
    category: 'macro',
    icon: 'BarChart2',
    componentPath: 'widgets/macro/JobsBreakdownWidget',
    defaultSize: { w: 5, h: 4 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: {},
  },
  'initial-claims': {
    id: 'initial-claims',
    name: 'Initial Claims',
    description: 'Weekly jobless claims trend',
    category: 'macro',
    icon: 'AlertTriangle',
    componentPath: 'widgets/macro/InitialClaimsWidget',
    defaultSize: { w: 5, h: 3 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: {},
  },
  'real-rates': {
    id: 'real-rates',
    name: 'Real Rates',
    description: 'TIPS / real interest rate environment',
    category: 'macro',
    icon: 'Percent',
    componentPath: 'widgets/macro/RealRatesWidget',
    defaultSize: { w: 5, h: 4 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: {},
  },
  'fed-balance-sheet': {
    id: 'fed-balance-sheet',
    name: 'Fed Balance Sheet',
    description: 'Federal Reserve balance sheet / QE/QT tracker',
    category: 'macro',
    icon: 'Building',
    componentPath: 'widgets/macro/FedBalanceSheetWidget',
    defaultSize: { w: 5, h: 4 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: {},
  },
  'fed-policy-stance': {
    id: 'fed-policy-stance',
    name: 'Fed Policy Stance',
    description: 'Hawkish/Dovish policy stance tracker',
    category: 'macro',
    icon: 'Scale',
    componentPath: 'widgets/macro/FedPolicyStanceWidget',
    defaultSize: { w: 4, h: 3 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: {},
  },
  'gdp-forecast': {
    id: 'gdp-forecast',
    name: 'GDP Forecast',
    description: 'GDP growth estimates and actuals',
    category: 'macro',
    icon: 'BarChart3',
    componentPath: 'widgets/macro/GDPForecastWidget',
    defaultSize: { w: 5, h: 4 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: {},
  },
  'pmi': {
    id: 'pmi',
    name: 'PMI',
    description: 'Manufacturing and services PMI indices',
    category: 'macro',
    icon: 'Factory',
    componentPath: 'widgets/macro/PMIWidget',
    defaultSize: { w: 5, h: 3 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: {},
  },

  // ── Portfolio ──────────────────────────────────────────────────────────────
  'portfolio-stats': {
    id: 'portfolio-stats',
    name: 'Portfolio Stats',
    description: 'Total value, P&L, return summary',
    category: 'portfolio',
    icon: 'Briefcase',
    componentPath: 'widgets/portfolio/PortfolioStatsWidget',
    defaultSize: { w: 4, h: 3 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: {},
  },
  'portfolio-holdings': {
    id: 'portfolio-holdings',
    name: 'Holdings',
    description: 'Current positions with P&L',
    category: 'portfolio',
    icon: 'List',
    componentPath: 'widgets/portfolio/PortfolioHoldingsWidget',
    defaultSize: { w: 8, h: 5 },
    minSize:     { w: 4, h: 3 },
    defaultConfig: {},
  },
  'portfolio-pnl-chart': {
    id: 'portfolio-pnl-chart',
    name: 'Portfolio P&L Chart',
    description: 'Historical P&L performance chart',
    category: 'portfolio',
    icon: 'TrendingUp',
    componentPath: 'widgets/portfolio/PortfolioPnLChartWidget',
    defaultSize: { w: 8, h: 5 },
    minSize:     { w: 4, h: 3 },
    defaultConfig: {},
  },
  'portfolio-balances': {
    id: 'portfolio-balances',
    name: 'Portfolio Balances',
    description: 'Cash and asset allocation balances',
    category: 'portfolio',
    icon: 'DollarSign',
    componentPath: 'widgets/portfolio/PortfolioBalancesWidget',
    defaultSize: { w: 4, h: 3 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: {},
  },
  'portfolio-positions': {
    id: 'portfolio-positions',
    name: 'Positions',
    description: 'Open positions with weights',
    category: 'portfolio',
    icon: 'BarChart2',
    componentPath: 'widgets/portfolio/PortfolioPositionsWidget',
    defaultSize: { w: 5, h: 4 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: {},
  },
  'portfolio-trade-history': {
    id: 'portfolio-trade-history',
    name: 'Trade History',
    description: 'Transaction log with filters',
    category: 'portfolio',
    icon: 'Clock',
    componentPath: 'widgets/portfolio/PortfolioTradeHistoryWidget',
    defaultSize: { w: 8, h: 5 },
    minSize:     { w: 4, h: 3 },
    defaultConfig: {},
  },
  'ownership-overview': {
    id: 'ownership-overview',
    name: 'Ownership Overview',
    description: 'Institutional vs retail ownership breakdown',
    category: 'stock',
    icon: 'PieChart',
    componentPath: 'widgets/stock/OwnershipOverviewWidget',
    defaultSize: { w: 4, h: 4 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: { symbol: 'AAPL' },
  },
  'ownership-institutional': {
    id: 'ownership-institutional',
    name: 'Institutional Ownership',
    description: 'Top institutional holders',
    category: 'stock',
    icon: 'Building2',
    componentPath: 'widgets/stock/OwnershipInstitutionalWidget',
    defaultSize: { w: 5, h: 4 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: { symbol: 'AAPL' },
  },
  'ownership-insider': {
    id: 'ownership-insider',
    name: 'Insider Ownership',
    description: 'Insider ownership percentage and changes',
    category: 'stock',
    icon: 'UserCheck',
    componentPath: 'widgets/stock/OwnershipInsiderWidget',
    defaultSize: { w: 5, h: 4 },
    minSize:     { w: 3, h: 3 },
    defaultConfig: { symbol: 'AAPL' },
  },
  'resizable-stock': {
    id: 'resizable-stock',
    name: 'Stock Mini Widget',
    description: 'Compact stock quote with mini chart',
    category: 'stock',
    icon: 'TrendingUp',
    componentPath: 'widgets/ResizableStockWidget',
    defaultSize: { w: 3, h: 4 },
    minSize:     { w: 2, h: 3 },
    defaultConfig: { symbol: 'AAPL' },
  },
};

// ── Categories ─────────────────────────────────────────────────────────────────
export const WIDGET_CATEGORIES = {
  stock: {
    label: 'Stock Analysis',
    icon: 'TrendingUp',
    widgets: Object.values(WIDGET_REGISTRY).filter(w => w.category === 'stock').map(w => w.id),
  },
  macro: {
    label: 'Macro',
    icon: 'Globe',
    widgets: Object.values(WIDGET_REGISTRY).filter(w => w.category === 'macro').map(w => w.id),
  },
  portfolio: {
    label: 'Portfolio',
    icon: 'Briefcase',
    widgets: Object.values(WIDGET_REGISTRY).filter(w => w.category === 'portfolio').map(w => w.id),
  },
  market: {
    label: 'Market',
    icon: 'BarChart2',
    widgets: Object.values(WIDGET_REGISTRY).filter(w => w.category === 'market').map(w => w.id),
  },
};

export default WIDGET_REGISTRY;
