"""baseline current schema

Revision ID: 8e3578555658
Revises: 
Create Date: 2026-09-21 21:34:11.615521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e3578555658'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mbs_in_article',
    sa.Column('news_id', sa.String(length=50), nullable=False),
    sa.Column('base_ymd', sa.Date(), nullable=False),
    sa.Column('source_cd', sa.String(length=50), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('publish_dt', sa.DateTime(), nullable=True),
    sa.Column('ingest_batch_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('news_id')
    )
    with op.batch_alter_table('mbs_in_article', schema=None) as batch_op:
        batch_op.create_index('idx_in_article_base_ymd', ['base_ymd'], unique=False)
        batch_op.create_index('idx_in_article_batch', ['ingest_batch_id'], unique=False)
        batch_op.create_index('idx_in_article_source', ['source_cd', 'base_ymd'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_article_base_ymd'), ['base_ymd'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_article_ingest_batch_id'), ['ingest_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_article_publish_dt'), ['publish_dt'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_article_source_cd'), ['source_cd'], unique=False)

    op.create_table('mbs_in_bond_issuance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issuer_cd', sa.String(length=20), nullable=True),
    sa.Column('issuer_nm', sa.String(length=200), nullable=True),
    sa.Column('bond_type', sa.String(length=50), nullable=True),
    sa.Column('issuance_amount', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('coupon_rate', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('base_ymd', sa.Date(), nullable=False),
    sa.Column('ingest_batch_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mbs_in_bond_issuance', schema=None) as batch_op:
        batch_op.create_index('idx_in_bond_issuance_issue_date', ['issue_date'], unique=False)
        batch_op.create_index('idx_in_bond_issuance_issuer', ['issuer_cd', 'issue_date'], unique=False)
        batch_op.create_index('idx_in_bond_issuance_type', ['bond_type', 'issue_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_bond_issuance_base_ymd'), ['base_ymd'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_bond_issuance_bond_type'), ['bond_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_bond_issuance_ingest_batch_id'), ['ingest_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_bond_issuance_issue_date'), ['issue_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_bond_issuance_issuer_cd'), ['issuer_cd'], unique=False)

    op.create_table('mbs_in_bond_stbd',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bond_cd', sa.String(length=20), nullable=False),
    sa.Column('bond_nm', sa.String(length=100), nullable=True),
    sa.Column('bond_type', sa.String(length=50), nullable=True),
    sa.Column('maturity', sa.String(length=20), nullable=True),
    sa.Column('curr', sa.String(length=10), nullable=True),
    sa.Column('close_price', sa.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('yield_rate', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('change_rate', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('base_ymd', sa.Date(), nullable=False),
    sa.Column('ingest_batch_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bond_cd', 'base_ymd', name='uq_bond_date')
    )
    with op.batch_alter_table('mbs_in_bond_stbd', schema=None) as batch_op:
        batch_op.create_index('idx_in_bond_base_ymd', ['base_ymd'], unique=False)
        batch_op.create_index('idx_in_bond_cd_date', ['bond_cd', 'base_ymd'], unique=False)
        batch_op.create_index('idx_in_bond_type', ['bond_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_bond_stbd_base_ymd'), ['base_ymd'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_bond_stbd_bond_cd'), ['bond_cd'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_bond_stbd_bond_type'), ['bond_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_bond_stbd_ingest_batch_id'), ['ingest_batch_id'], unique=False)

    op.create_table('mbs_in_cmdty_stbd',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cmdty_cd', sa.String(length=20), nullable=False),
    sa.Column('cmdty_nm', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('curr', sa.String(length=10), nullable=True),
    sa.Column('close_price', sa.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('change_rate', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('base_ymd', sa.Date(), nullable=False),
    sa.Column('ingest_batch_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cmdty_cd', 'base_ymd', name='uq_cmdty_date')
    )
    with op.batch_alter_table('mbs_in_cmdty_stbd', schema=None) as batch_op:
        batch_op.create_index('idx_in_cmdty_base_ymd', ['base_ymd'], unique=False)
        batch_op.create_index('idx_in_cmdty_cd_date', ['cmdty_cd', 'base_ymd'], unique=False)
        batch_op.create_index('idx_in_cmdty_sector', ['sector'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_cmdty_stbd_base_ymd'), ['base_ymd'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_cmdty_stbd_cmdty_cd'), ['cmdty_cd'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_cmdty_stbd_ingest_batch_id'), ['ingest_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_cmdty_stbd_sector'), ['sector'], unique=False)

    op.create_table('mbs_in_etf_stbd',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('etf_cd', sa.String(length=20), nullable=False),
    sa.Column('etf_nm', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('curr', sa.String(length=10), nullable=True),
    sa.Column('close_price', sa.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('change_rate', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('base_ymd', sa.Date(), nullable=False),
    sa.Column('ingest_batch_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etf_cd', 'base_ymd', name='uq_etf_date')
    )
    with op.batch_alter_table('mbs_in_etf_stbd', schema=None) as batch_op:
        batch_op.create_index('idx_in_etf_base_ymd', ['base_ymd'], unique=False)
        batch_op.create_index('idx_in_etf_cd_date', ['etf_cd', 'base_ymd'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_etf_stbd_base_ymd'), ['base_ymd'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_etf_stbd_etf_cd'), ['etf_cd'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_etf_stbd_ingest_batch_id'), ['ingest_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_etf_stbd_sector'), ['sector'], unique=False)

    op.create_table('mbs_in_financial_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stk_cd', sa.String(length=20), nullable=False),
    sa.Column('stk_nm', sa.String(length=100), nullable=True),
    sa.Column('debt_to_asset', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('debt_to_equity', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('current_ratio', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('quick_ratio', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('roe', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('roa', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('profit_margin', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('pe_ratio', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('pb_ratio', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('market_cap', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('fiscal_period', sa.String(length=20), nullable=True),
    sa.Column('base_ymd', sa.Date(), nullable=False),
    sa.Column('ingest_batch_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stk_cd', 'base_ymd', 'fiscal_period', name='uq_financial_date')
    )
    with op.batch_alter_table('mbs_in_financial_metrics', schema=None) as batch_op:
        batch_op.create_index('idx_in_financial_base_ymd', ['base_ymd'], unique=False)
        batch_op.create_index('idx_in_financial_stk_cd', ['stk_cd', 'base_ymd'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_financial_metrics_base_ymd'), ['base_ymd'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_financial_metrics_ingest_batch_id'), ['ingest_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_financial_metrics_stk_cd'), ['stk_cd'], unique=False)

    op.create_table('mbs_in_indx_member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('indx_cd', sa.String(length=50), nullable=False),
    sa.Column('stk_cd', sa.String(length=20), nullable=False),
    sa.Column('stk_nm', sa.String(length=200), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('sub_sector', sa.String(length=100), nullable=True),
    sa.Column('date_added', sa.Date(), nullable=True),
    sa.Column('date_removed', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indx_cd', 'stk_cd', name='uq_indx_member')
    )
    with op.batch_alter_table('mbs_in_indx_member', schema=None) as batch_op:
        batch_op.create_index('idx_indx_member_indx', ['indx_cd', 'is_current'], unique=False)
        batch_op.create_index('idx_indx_member_stk', ['stk_cd'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_indx_member_indx_cd'), ['indx_cd'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_indx_member_is_current'), ['is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_indx_member_stk_cd'), ['stk_cd'], unique=False)

    op.create_table('mbs_in_indx_stbd',
    sa.Column('indx_cd', sa.String(length=50), nullable=False),
    sa.Column('indx_nm', sa.String(length=200), nullable=False),
    sa.Column('indx_type', sa.String(length=20), nullable=False),
    sa.Column('fmp_endpoint', sa.String(length=100), nullable=True),
    sa.Column('api_symbol', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('indx_cd')
    )
    with op.batch_alter_table('mbs_in_indx_stbd', schema=None) as batch_op:
        batch_op.create_index('idx_indx_active', ['is_active'], unique=False)
        batch_op.create_index('idx_indx_order', ['display_order'], unique=False)
        batch_op.create_index('idx_indx_type', ['indx_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_indx_stbd_indx_type'), ['indx_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_indx_stbd_is_active'), ['is_active'], unique=False)

    op.create_table('mbs_in_insti_hold',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('institution_key', sa.String(length=100), nullable=False),
    sa.Column('is_sold', sa.Boolean(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('cusip', sa.String(length=20), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('shares', sa.BigInteger(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('prev_shares', sa.BigInteger(), nullable=True),
    sa.Column('prev_value', sa.Float(), nullable=True),
    sa.Column('share_change', sa.BigInteger(), nullable=True),
    sa.Column('share_change_pct', sa.Float(), nullable=True),
    sa.Column('value_change', sa.Float(), nullable=True),
    sa.Column('value_change_pct', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mbs_in_insti_hold', schema=None) as batch_op:
        batch_op.create_index('ix_insti_hold_key_sold', ['institution_key', 'is_sold'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_insti_hold_institution_key'), ['institution_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_insti_hold_is_sold'), ['is_sold'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_insti_hold_symbol'), ['symbol'], unique=False)

    op.create_table('mbs_in_insti_mst',
    sa.Column('institution_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('manager', sa.String(length=300), nullable=True),
    sa.Column('cik', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('institution_key')
    )
    with op.batch_alter_table('mbs_in_insti_mst', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mbs_in_insti_mst_cik'), ['cik'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_insti_mst_is_active'), ['is_active'], unique=False)

    op.create_table('mbs_in_insti_perf',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('institution_key', sa.String(length=100), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('filing_date', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('manager', sa.String(length=300), nullable=True),
    sa.Column('return_pct', sa.Float(), nullable=True),
    sa.Column('cumulative_return_pct', sa.Float(), nullable=True),
    sa.Column('aum_change_pct', sa.Float(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('num_holdings', sa.Integer(), nullable=True),
    sa.Column('coverage_pct', sa.Float(), nullable=True),
    sa.Column('derivative_weight_pct', sa.Float(), nullable=True),
    sa.Column('matched_positions', sa.Integer(), nullable=True),
    sa.Column('excluded_positions', sa.Integer(), nullable=True),
    sa.Column('top_contributor', sa.String(length=300), nullable=True),
    sa.Column('top_contributor_pct', sa.Float(), nullable=True),
    sa.Column('top_detractor', sa.String(length=300), nullable=True),
    sa.Column('top_detractor_pct', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mbs_in_insti_perf', schema=None) as batch_op:
        batch_op.create_index('ix_insti_perf_key_period', ['institution_key', 'period'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_insti_perf_institution_key'), ['institution_key'], unique=False)

    op.create_table('mbs_in_insti_port',
    sa.Column('institution_key', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=120), nullable=True),
    sa.Column('manager', sa.String(length=300), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('num_holdings', sa.Integer(), nullable=True),
    sa.Column('filing_date', sa.String(length=20), nullable=True),
    sa.Column('period_end', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('previous_filing_date', sa.String(length=20), nullable=True),
    sa.Column('previous_value', sa.Float(), nullable=True),
    sa.Column('value_change', sa.Float(), nullable=True),
    sa.Column('value_change_pct', sa.Float(), nullable=True),
    sa.Column('num_new_positions', sa.Integer(), nullable=True),
    sa.Column('num_sold_out', sa.Integer(), nullable=True),
    sa.Column('num_increased', sa.Integer(), nullable=True),
    sa.Column('num_decreased', sa.Integer(), nullable=True),
    sa.Column('turnover', sa.Float(), nullable=True),
    sa.Column('performance', sa.JSON(), nullable=True),
    sa.Column('top_sectors', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('institution_key')
    )
    with op.batch_alter_table('mbs_in_insti_port', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mbs_in_insti_port_period_end'), ['period_end'], unique=False)

    op.create_table('mbs_in_research_rpt',
    sa.Column('report_id', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('num_pages', sa.Integer(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('report_id')
    )
    with op.batch_alter_table('mbs_in_research_rpt', schema=None) as batch_op:
        batch_op.create_index('idx_research_rpt_published', ['published_date'], unique=False)
        batch_op.create_index('idx_research_rpt_symbol_type', ['symbol', 'report_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_research_rpt_published_date'), ['published_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_research_rpt_report_type'), ['report_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_research_rpt_symbol'), ['symbol'], unique=False)

    op.create_table('mbs_in_stbd_mst',
    sa.Column('ticker_cd', sa.String(length=20), nullable=False),
    sa.Column('ticker_nm', sa.String(length=200), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('curr', sa.String(length=10), nullable=True),
    sa.Column('bond_type', sa.String(length=50), nullable=True),
    sa.Column('maturity', sa.String(length=20), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ticker_cd')
    )
    with op.batch_alter_table('mbs_in_stbd_mst', schema=None) as batch_op:
        batch_op.create_index('idx_stbd_mst_active', ['is_active'], unique=False)
        batch_op.create_index('idx_stbd_mst_asset_type', ['asset_type'], unique=False)
        batch_op.create_index('idx_stbd_mst_sector', ['sector'], unique=False)
        batch_op.create_index('idx_stbd_mst_start_date', ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_stbd_mst_asset_type'), ['asset_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_stbd_mst_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_stbd_mst_sector'), ['sector'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_stbd_mst_start_date'), ['start_date'], unique=False)

    op.create_table('mbs_in_stk_profile',
    sa.Column('stk_cd', sa.String(length=20), nullable=False),
    sa.Column('stk_nm', sa.String(length=200), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('ceo', sa.String(length=100), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('ipo_date', sa.Date(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('market_cap', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('beta', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('in_sp500', sa.Boolean(), nullable=True),
    sa.Column('in_nasdaq100', sa.Boolean(), nullable=True),
    sa.Column('in_dow30', sa.Boolean(), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('stk_cd')
    )
    with op.batch_alter_table('mbs_in_stk_profile', schema=None) as batch_op:
        batch_op.create_index('idx_stk_profile_industry', ['industry'], unique=False)
        batch_op.create_index('idx_stk_profile_sector', ['sector'], unique=False)
        batch_op.create_index('idx_stk_profile_sp500', ['in_sp500'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_stk_profile_in_sp500'), ['in_sp500'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_stk_profile_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_stk_profile_sector'), ['sector'], unique=False)

    op.create_table('mbs_in_stk_relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stk_cd', sa.String(length=20), nullable=False),
    sa.Column('related_cd', sa.String(length=20), nullable=False),
    sa.Column('relation_type', sa.String(length=30), nullable=False),
    sa.Column('related_nm', sa.String(length=200), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('confidence', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stk_cd', 'related_cd', 'relation_type', name='uq_stk_relation')
    )
    with op.batch_alter_table('mbs_in_stk_relations', schema=None) as batch_op:
        batch_op.create_index('idx_stk_relations_stk', ['stk_cd'], unique=False)
        batch_op.create_index('idx_stk_relations_type', ['stk_cd', 'relation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_stk_relations_related_cd'), ['related_cd'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_stk_relations_relation_type'), ['relation_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_stk_relations_stk_cd'), ['stk_cd'], unique=False)

    op.create_table('mbs_in_stk_stbd',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stk_cd', sa.String(length=20), nullable=False),
    sa.Column('stk_nm', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('curr', sa.String(length=10), nullable=True),
    sa.Column('close_price', sa.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('change_rate', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('base_ymd', sa.Date(), nullable=False),
    sa.Column('ingest_batch_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stk_cd', 'base_ymd', name='uq_stk_date')
    )
    with op.batch_alter_table('mbs_in_stk_stbd', schema=None) as batch_op:
        batch_op.create_index('idx_in_stk_base_ymd', ['base_ymd'], unique=False)
        batch_op.create_index('idx_in_stk_cd_date', ['stk_cd', 'base_ymd'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_stk_stbd_base_ymd'), ['base_ymd'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_stk_stbd_ingest_batch_id'), ['ingest_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_stk_stbd_sector'), ['sector'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_in_stk_stbd_stk_cd'), ['stk_cd'], unique=False)

    op.create_table('menu_management',
    sa.Column('menu_id', sa.String(length=50), nullable=False),
    sa.Column('pkg_type', sa.String(length=50), nullable=False),
    sa.Column('menu_name', sa.String(length=100), nullable=False),
    sa.Column('menu_level', sa.Integer(), nullable=False),
    sa.Column('menu_icon', sa.String(length=50), nullable=True),
    sa.Column('menu_parent_id', sa.String(length=50), nullable=True),
    sa.Column('menu_path', sa.String(length=200), nullable=False),
    sa.Column('menu_script', sa.String(length=200), nullable=True),
    sa.Column('user_type_cd', sa.String(length=50), nullable=True),
    sa.Column('menu_desc', sa.Text(), nullable=True),
    sa.Column('display_seq', sa.Integer(), nullable=False),
    sa.Column('use_yn', sa.String(length=1), nullable=False),
    sa.Column('first_page_yn', sa.String(length=1), nullable=False),
    sa.Column('reg_date', sa.DateTime(), nullable=False),
    sa.Column('upd_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['menu_parent_id'], ['menu_management.menu_id'], ),
    sa.PrimaryKeyConstraint('menu_id')
    )
    with op.batch_alter_table('menu_management', schema=None) as batch_op:
        batch_op.create_index('idx_menu_parent_seq', ['menu_parent_id', 'display_seq'], unique=False)
        batch_op.create_index('idx_menu_pkg_level', ['pkg_type', 'menu_level'], unique=False)
        batch_op.create_index('idx_menu_use_yn', ['use_yn'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_management_display_seq'), ['display_seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_management_menu_level'), ['menu_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_management_menu_parent_id'), ['menu_parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_management_pkg_type'), ['pkg_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_menu_management_use_yn'), ['use_yn'], unique=False)

    op.create_table('quant_factor_catalog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_ko', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('sub', sa.String(length=50), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('examples', sa.Text(), nullable=True),
    sa.Column('strategic', sa.Text(), nullable=True),
    sa.Column('params', sa.Text(), nullable=False),
    sa.Column('availability', sa.String(length=20), nullable=False),
    sa.Column('backends', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('use_yn', sa.String(length=1), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quant_factor_catalog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quant_factor_catalog_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_quant_factor_catalog_key'), ['key'], unique=True)

    op.create_table('users',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_user_active', ['is_active'], unique=False)
        batch_op.create_index('idx_user_email', ['email'], unique=False)
        batch_op.create_index('idx_user_username', ['username'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('alerts',
    sa.Column('alert_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('alert_type', sa.String(length=20), nullable=False),
    sa.Column('ticker_cd', sa.String(length=20), nullable=True),
    sa.Column('condition_type', sa.String(length=20), nullable=True),
    sa.Column('threshold_value', sa.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notification_method', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('last_triggered', sa.DateTime(), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('idx_alert_active', ['is_active'], unique=False)
        batch_op.create_index('idx_alert_ticker', ['ticker_cd'], unique=False)
        batch_op.create_index('idx_alert_type', ['alert_type'], unique=False)
        batch_op.create_index('idx_alert_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_ticker_cd'), ['ticker_cd'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('mbs_proc_article',
    sa.Column('proc_id', sa.String(length=50), nullable=False),
    sa.Column('news_id', sa.String(length=50), nullable=False),
    sa.Column('stk_cd', sa.String(length=20), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('match_score', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('price_impact', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('sentiment_score', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('base_ymd', sa.Date(), nullable=False),
    sa.Column('source_batch_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['mbs_in_article.news_id'], ),
    sa.PrimaryKeyConstraint('proc_id')
    )
    with op.batch_alter_table('mbs_proc_article', schema=None) as batch_op:
        batch_op.create_index('idx_proc_base_ymd', ['base_ymd'], unique=False)
        batch_op.create_index('idx_proc_news_id', ['news_id'], unique=False)
        batch_op.create_index('idx_proc_sentiment', ['sentiment_score', 'base_ymd'], unique=False)
        batch_op.create_index('idx_proc_stk_cd', ['stk_cd', 'base_ymd'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_proc_article_base_ymd'), ['base_ymd'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_proc_article_news_id'), ['news_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_proc_article_source_batch_id'), ['source_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_proc_article_stk_cd'), ['stk_cd'], unique=False)

    op.create_table('portfolios',
    sa.Column('portfolio_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('benchmark', sa.String(length=20), nullable=True),
    sa.Column('rebalance_frequency', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('portfolio_id')
    )
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.create_index('idx_portfolio_default', ['user_id', 'is_default'], unique=False)
        batch_op.create_index('idx_portfolio_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolios_user_id'), ['user_id'], unique=False)

    op.create_table('quant_factors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('factor_type', sa.String(length=50), nullable=False),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quant_factors', schema=None) as batch_op:
        batch_op.create_index('idx_quant_factor_user', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_quant_factors_user_id'), ['user_id'], unique=False)

    op.create_table('saved_screeners',
    sa.Column('screener_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filters', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('run_frequency', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('screener_id')
    )
    with op.batch_alter_table('saved_screeners', schema=None) as batch_op:
        batch_op.create_index('idx_screener_active', ['is_active'], unique=False)
        batch_op.create_index('idx_screener_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_screeners_user_id'), ['user_id'], unique=False)

    op.create_table('user_api_keys',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('enc_value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'provider')
    )
    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.create_index('idx_user_api_keys_user', ['user_id'], unique=False)

    op.create_table('user_backtest_items',
    sa.Column('item_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('spec', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('user_id', 'kind', 'name', name='uq_bt_item_user_kind_name')
    )
    with op.batch_alter_table('user_backtest_items', schema=None) as batch_op:
        batch_op.create_index('idx_bt_item_user_kind', ['user_id', 'kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_backtest_items_user_id'), ['user_id'], unique=False)

    op.create_table('user_backtest_runs',
    sa.Column('run_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('strategy_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('metrics', sa.Text(), nullable=False),
    sa.Column('equity', sa.Text(), nullable=False),
    sa.Column('trades', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    with op.batch_alter_table('user_backtest_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_backtest_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_backtest_runs_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_backtest_runs_user_id'), ['user_id'], unique=False)

    op.create_table('user_notes',
    sa.Column('note_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('ticker_cd', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    with op.batch_alter_table('user_notes', schema=None) as batch_op:
        batch_op.create_index('idx_note_ticker', ['user_id', 'ticker_cd'], unique=False)
        batch_op.create_index('idx_note_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_notes_ticker_cd'), ['ticker_cd'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_notes_user_id'), ['user_id'], unique=False)

    op.create_table('user_workspaces',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('screen', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('layout', sa.Text(), nullable=True),
    sa.Column('widgets', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_workspaces', schema=None) as batch_op:
        batch_op.create_index('idx_workspace_user_screen', ['user_id', 'screen'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_workspaces_user_id'), ['user_id'], unique=False)

    op.create_table('watchlists',
    sa.Column('watchlist_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tickers', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('watchlist_id')
    )
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.create_index('idx_watchlist_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlists_user_id'), ['user_id'], unique=False)

    op.create_table('alert_history',
    sa.Column('history_id', sa.String(length=50), nullable=False),
    sa.Column('alert_id', sa.String(length=50), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('triggered_value', sa.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.alert_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.create_index('idx_alert_history_alert', ['alert_id'], unique=False)
        batch_op.create_index('idx_alert_history_triggered', ['triggered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_history_alert_id'), ['alert_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_history_triggered_at'), ['triggered_at'], unique=False)

    op.create_table('holdings',
    sa.Column('holding_id', sa.String(length=50), nullable=False),
    sa.Column('portfolio_id', sa.String(length=50), nullable=False),
    sa.Column('ticker_cd', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('avg_cost', sa.DECIMAL(precision=20, scale=4), nullable=False),
    sa.Column('current_price', sa.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('total_cost', sa.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('market_value', sa.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('unrealized_pnl', sa.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('unrealized_pnl_pct', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], ),
    sa.PrimaryKeyConstraint('holding_id'),
    sa.UniqueConstraint('portfolio_id', 'ticker_cd', name='uq_portfolio_ticker')
    )
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.create_index('idx_holding_portfolio', ['portfolio_id'], unique=False)
        batch_op.create_index('idx_holding_ticker', ['ticker_cd'], unique=False)
        batch_op.create_index(batch_op.f('ix_holdings_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_holdings_ticker_cd'), ['ticker_cd'], unique=False)

    op.create_table('mbs_calc_metric',
    sa.Column('calc_id', sa.String(length=50), nullable=False),
    sa.Column('stk_cd', sa.String(length=20), nullable=False),
    sa.Column('base_ymd', sa.Date(), nullable=False),
    sa.Column('metric_type', sa.String(length=20), nullable=False),
    sa.Column('metric_val', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('source_proc_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_proc_id'], ['mbs_proc_article.proc_id'], ),
    sa.PrimaryKeyConstraint('calc_id')
    )
    with op.batch_alter_table('mbs_calc_metric', schema=None) as batch_op:
        batch_op.create_index('idx_calc_base_ymd', ['base_ymd'], unique=False)
        batch_op.create_index('idx_calc_metric_type', ['metric_type', 'base_ymd'], unique=False)
        batch_op.create_index('idx_calc_source_proc', ['source_proc_id'], unique=False)
        batch_op.create_index('idx_calc_stk_cd', ['stk_cd', 'base_ymd'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_calc_metric_base_ymd'), ['base_ymd'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_calc_metric_metric_type'), ['metric_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_calc_metric_source_proc_id'), ['source_proc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_calc_metric_stk_cd'), ['stk_cd'], unique=False)

    op.create_table('transactions',
    sa.Column('transaction_id', sa.String(length=50), nullable=False),
    sa.Column('portfolio_id', sa.String(length=50), nullable=False),
    sa.Column('ticker_cd', sa.String(length=20), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=20, scale=4), nullable=False),
    sa.Column('commission', sa.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('tax', sa.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('total_amount', sa.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('idx_transaction_date', ['transaction_date'], unique=False)
        batch_op.create_index('idx_transaction_portfolio', ['portfolio_id'], unique=False)
        batch_op.create_index('idx_transaction_ticker', ['ticker_cd'], unique=False)
        batch_op.create_index('idx_transaction_type', ['transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_ticker_cd'), ['ticker_cd'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_date'), ['transaction_date'], unique=False)

    op.create_table('watchlist_items',
    sa.Column('item_id', sa.String(length=50), nullable=False),
    sa.Column('watchlist_id', sa.String(length=50), nullable=False),
    sa.Column('ticker_cd', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.watchlist_id'], ),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('watchlist_id', 'ticker_cd', name='uq_watchlist_ticker')
    )
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.create_index('idx_watchlist_items_ticker', ['ticker_cd'], unique=False)
        batch_op.create_index('idx_watchlist_items_watchlist', ['watchlist_id', 'sort_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_items_sort_order'), ['sort_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_items_ticker_cd'), ['ticker_cd'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_items_watchlist_id'), ['watchlist_id'], unique=False)

    op.create_table('mbs_rcmd_result',
    sa.Column('rcmd_id', sa.String(length=50), nullable=False),
    sa.Column('ref_news_id', sa.String(length=50), nullable=True),
    sa.Column('ref_stk_cd', sa.String(length=20), nullable=True),
    sa.Column('ref_calc_id', sa.String(length=50), nullable=True),
    sa.Column('rcmd_type', sa.String(length=20), nullable=False),
    sa.Column('score', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('base_ymd', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ref_calc_id'], ['mbs_calc_metric.calc_id'], ),
    sa.ForeignKeyConstraint(['ref_news_id'], ['mbs_in_article.news_id'], ),
    sa.PrimaryKeyConstraint('rcmd_id')
    )
    with op.batch_alter_table('mbs_rcmd_result', schema=None) as batch_op:
        batch_op.create_index('idx_rcmd_base_ymd', ['base_ymd'], unique=False)
        batch_op.create_index('idx_rcmd_score', ['score', 'base_ymd'], unique=False)
        batch_op.create_index('idx_rcmd_stk_cd', ['ref_stk_cd', 'base_ymd'], unique=False)
        batch_op.create_index('idx_rcmd_type', ['rcmd_type', 'base_ymd'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_rcmd_result_base_ymd'), ['base_ymd'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_rcmd_result_rcmd_type'), ['rcmd_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_rcmd_result_ref_calc_id'), ['ref_calc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_rcmd_result_ref_news_id'), ['ref_news_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mbs_rcmd_result_ref_stk_cd'), ['ref_stk_cd'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mbs_rcmd_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mbs_rcmd_result_ref_stk_cd'))
        batch_op.drop_index(batch_op.f('ix_mbs_rcmd_result_ref_news_id'))
        batch_op.drop_index(batch_op.f('ix_mbs_rcmd_result_ref_calc_id'))
        batch_op.drop_index(batch_op.f('ix_mbs_rcmd_result_rcmd_type'))
        batch_op.drop_index(batch_op.f('ix_mbs_rcmd_result_base_ymd'))
        batch_op.drop_index('idx_rcmd_type')
        batch_op.drop_index('idx_rcmd_stk_cd')
        batch_op.drop_index('idx_rcmd_score')
        batch_op.drop_index('idx_rcmd_base_ymd')

    op.drop_table('mbs_rcmd_result')
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_items_watchlist_id'))
        batch_op.drop_index(batch_op.f('ix_watchlist_items_ticker_cd'))
        batch_op.drop_index(batch_op.f('ix_watchlist_items_sort_order'))
        batch_op.drop_index('idx_watchlist_items_watchlist')
        batch_op.drop_index('idx_watchlist_items_ticker')

    op.drop_table('watchlist_items')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_ticker_cd'))
        batch_op.drop_index(batch_op.f('ix_transactions_portfolio_id'))
        batch_op.drop_index('idx_transaction_type')
        batch_op.drop_index('idx_transaction_ticker')
        batch_op.drop_index('idx_transaction_portfolio')
        batch_op.drop_index('idx_transaction_date')

    op.drop_table('transactions')
    with op.batch_alter_table('mbs_calc_metric', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mbs_calc_metric_stk_cd'))
        batch_op.drop_index(batch_op.f('ix_mbs_calc_metric_source_proc_id'))
        batch_op.drop_index(batch_op.f('ix_mbs_calc_metric_metric_type'))
        batch_op.drop_index(batch_op.f('ix_mbs_calc_metric_base_ymd'))
        batch_op.drop_index('idx_calc_stk_cd')
        batch_op.drop_index('idx_calc_source_proc')
        batch_op.drop_index('idx_calc_metric_type')
        batch_op.drop_index('idx_calc_base_ymd')

    op.drop_table('mbs_calc_metric')
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holdings_ticker_cd'))
        batch_op.drop_index(batch_op.f('ix_holdings_portfolio_id'))
        batch_op.drop_index('idx_holding_ticker')
        batch_op.drop_index('idx_holding_portfolio')

    op.drop_table('holdings')
    with op.batch_alter_table('alert_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_history_triggered_at'))
        batch_op.drop_index(batch_op.f('ix_alert_history_alert_id'))
        batch_op.drop_index('idx_alert_history_triggered')
        batch_op.drop_index('idx_alert_history_alert')

    op.drop_table('alert_history')
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlists_user_id'))
        batch_op.drop_index('idx_watchlist_user')

    op.drop_table('watchlists')
    with op.batch_alter_table('user_workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_workspaces_user_id'))
        batch_op.drop_index('idx_workspace_user_screen')

    op.drop_table('user_workspaces')
    with op.batch_alter_table('user_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_notes_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_notes_ticker_cd'))
        batch_op.drop_index('idx_note_user')
        batch_op.drop_index('idx_note_ticker')

    op.drop_table('user_notes')
    with op.batch_alter_table('user_backtest_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_backtest_runs_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_backtest_runs_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_user_backtest_runs_created_at'))

    op.drop_table('user_backtest_runs')
    with op.batch_alter_table('user_backtest_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_backtest_items_user_id'))
        batch_op.drop_index('idx_bt_item_user_kind')

    op.drop_table('user_backtest_items')
    with op.batch_alter_table('user_api_keys', schema=None) as batch_op:
        batch_op.drop_index('idx_user_api_keys_user')

    op.drop_table('user_api_keys')
    with op.batch_alter_table('saved_screeners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_screeners_user_id'))
        batch_op.drop_index('idx_screener_user')
        batch_op.drop_index('idx_screener_active')

    op.drop_table('saved_screeners')
    with op.batch_alter_table('quant_factors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quant_factors_user_id'))
        batch_op.drop_index('idx_quant_factor_user')

    op.drop_table('quant_factors')
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolios_user_id'))
        batch_op.drop_index('idx_portfolio_user')
        batch_op.drop_index('idx_portfolio_default')

    op.drop_table('portfolios')
    with op.batch_alter_table('mbs_proc_article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mbs_proc_article_stk_cd'))
        batch_op.drop_index(batch_op.f('ix_mbs_proc_article_source_batch_id'))
        batch_op.drop_index(batch_op.f('ix_mbs_proc_article_news_id'))
        batch_op.drop_index(batch_op.f('ix_mbs_proc_article_base_ymd'))
        batch_op.drop_index('idx_proc_stk_cd')
        batch_op.drop_index('idx_proc_sentiment')
        batch_op.drop_index('idx_proc_news_id')
        batch_op.drop_index('idx_proc_base_ymd')

    op.drop_table('mbs_proc_article')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_ticker_cd'))
        batch_op.drop_index(batch_op.f('ix_alerts_is_active'))
        batch_op.drop_index(batch_op.f('ix_alerts_alert_type'))
        batch_op.drop_index('idx_alert_user')
        batch_op.drop_index('idx_alert_type')
        batch_op.drop_index('idx_alert_ticker')
        batch_op.drop_index('idx_alert_active')

    op.drop_table('alerts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('idx_user_username')
        batch_op.drop_index('idx_user_email')
        batch_op.drop_index('idx_user_active')

    op.drop_table('users')
    with op.batch_alter_table('quant_factor_catalog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quant_factor_catalog_key'))
        batch_op.drop_index(batch_op.f('ix_quant_factor_catalog_category'))

    op.drop_table('quant_factor_catalog')
    with op.batch_alter_table('menu_management', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_management_use_yn'))
        batch_op.drop_index(batch_op.f('ix_menu_management_pkg_type'))
        batch_op.drop_index(batch_op.f('ix_menu_management_menu_parent_id'))
        batch_op.drop_index(batch_op.f('ix_menu_management_menu_level'))
        batch_op.drop_index(batch_op.f('ix_menu_management_display_seq'))
        batch_op.drop_index('idx_menu_use_yn')
        batch_op.drop_index('idx_menu_pkg_level')
        batch_op.drop_index('idx_menu_parent_seq')

    op.drop_table('menu_management')
    with op.batch_alter_table('mbs_in_stk_stbd', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mbs_in_stk_stbd_stk_cd'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_stk_stbd_sector'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_stk_stbd_ingest_batch_id'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_stk_stbd_base_ymd'))
        batch_op.drop_index('idx_in_stk_cd_date')
        batch_op.drop_index('idx_in_stk_base_ymd')

    op.drop_table('mbs_in_stk_stbd')
    with op.batch_alter_table('mbs_in_stk_relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mbs_in_stk_relations_stk_cd'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_stk_relations_relation_type'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_stk_relations_related_cd'))
        batch_op.drop_index('idx_stk_relations_type')
        batch_op.drop_index('idx_stk_relations_stk')

    op.drop_table('mbs_in_stk_relations')
    with op.batch_alter_table('mbs_in_stk_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mbs_in_stk_profile_sector'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_stk_profile_industry'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_stk_profile_in_sp500'))
        batch_op.drop_index('idx_stk_profile_sp500')
        batch_op.drop_index('idx_stk_profile_sector')
        batch_op.drop_index('idx_stk_profile_industry')

    op.drop_table('mbs_in_stk_profile')
    with op.batch_alter_table('mbs_in_stbd_mst', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mbs_in_stbd_mst_start_date'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_stbd_mst_sector'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_stbd_mst_is_active'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_stbd_mst_asset_type'))
        batch_op.drop_index('idx_stbd_mst_start_date')
        batch_op.drop_index('idx_stbd_mst_sector')
        batch_op.drop_index('idx_stbd_mst_asset_type')
        batch_op.drop_index('idx_stbd_mst_active')

    op.drop_table('mbs_in_stbd_mst')
    with op.batch_alter_table('mbs_in_research_rpt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mbs_in_research_rpt_symbol'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_research_rpt_report_type'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_research_rpt_published_date'))
        batch_op.drop_index('idx_research_rpt_symbol_type')
        batch_op.drop_index('idx_research_rpt_published')

    op.drop_table('mbs_in_research_rpt')
    with op.batch_alter_table('mbs_in_insti_port', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mbs_in_insti_port_period_end'))

    op.drop_table('mbs_in_insti_port')
    with op.batch_alter_table('mbs_in_insti_perf', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mbs_in_insti_perf_institution_key'))
        batch_op.drop_index('ix_insti_perf_key_period')

    op.drop_table('mbs_in_insti_perf')
    with op.batch_alter_table('mbs_in_insti_mst', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mbs_in_insti_mst_is_active'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_insti_mst_cik'))

    op.drop_table('mbs_in_insti_mst')
    with op.batch_alter_table('mbs_in_insti_hold', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mbs_in_insti_hold_symbol'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_insti_hold_is_sold'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_insti_hold_institution_key'))
        batch_op.drop_index('ix_insti_hold_key_sold')

    op.drop_table('mbs_in_insti_hold')
    with op.batch_alter_table('mbs_in_indx_stbd', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mbs_in_indx_stbd_is_active'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_indx_stbd_indx_type'))
        batch_op.drop_index('idx_indx_type')
        batch_op.drop_index('idx_indx_order')
        batch_op.drop_index('idx_indx_active')

    op.drop_table('mbs_in_indx_stbd')
    with op.batch_alter_table('mbs_in_indx_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mbs_in_indx_member_stk_cd'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_indx_member_is_current'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_indx_member_indx_cd'))
        batch_op.drop_index('idx_indx_member_stk')
        batch_op.drop_index('idx_indx_member_indx')

    op.drop_table('mbs_in_indx_member')
    with op.batch_alter_table('mbs_in_financial_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mbs_in_financial_metrics_stk_cd'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_financial_metrics_ingest_batch_id'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_financial_metrics_base_ymd'))
        batch_op.drop_index('idx_in_financial_stk_cd')
        batch_op.drop_index('idx_in_financial_base_ymd')

    op.drop_table('mbs_in_financial_metrics')
    with op.batch_alter_table('mbs_in_etf_stbd', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mbs_in_etf_stbd_sector'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_etf_stbd_ingest_batch_id'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_etf_stbd_etf_cd'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_etf_stbd_base_ymd'))
        batch_op.drop_index('idx_in_etf_cd_date')
        batch_op.drop_index('idx_in_etf_base_ymd')

    op.drop_table('mbs_in_etf_stbd')
    with op.batch_alter_table('mbs_in_cmdty_stbd', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mbs_in_cmdty_stbd_sector'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_cmdty_stbd_ingest_batch_id'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_cmdty_stbd_cmdty_cd'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_cmdty_stbd_base_ymd'))
        batch_op.drop_index('idx_in_cmdty_sector')
        batch_op.drop_index('idx_in_cmdty_cd_date')
        batch_op.drop_index('idx_in_cmdty_base_ymd')

    op.drop_table('mbs_in_cmdty_stbd')
    with op.batch_alter_table('mbs_in_bond_stbd', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mbs_in_bond_stbd_ingest_batch_id'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_bond_stbd_bond_type'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_bond_stbd_bond_cd'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_bond_stbd_base_ymd'))
        batch_op.drop_index('idx_in_bond_type')
        batch_op.drop_index('idx_in_bond_cd_date')
        batch_op.drop_index('idx_in_bond_base_ymd')

    op.drop_table('mbs_in_bond_stbd')
    with op.batch_alter_table('mbs_in_bond_issuance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mbs_in_bond_issuance_issuer_cd'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_bond_issuance_issue_date'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_bond_issuance_ingest_batch_id'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_bond_issuance_bond_type'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_bond_issuance_base_ymd'))
        batch_op.drop_index('idx_in_bond_issuance_type')
        batch_op.drop_index('idx_in_bond_issuance_issuer')
        batch_op.drop_index('idx_in_bond_issuance_issue_date')

    op.drop_table('mbs_in_bond_issuance')
    with op.batch_alter_table('mbs_in_article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mbs_in_article_source_cd'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_article_publish_dt'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_article_ingest_batch_id'))
        batch_op.drop_index(batch_op.f('ix_mbs_in_article_base_ymd'))
        batch_op.drop_index('idx_in_article_source')
        batch_op.drop_index('idx_in_article_batch')
        batch_op.drop_index('idx_in_article_base_ymd')

    op.drop_table('mbs_in_article')
    # ### end Alembic commands ###
